services:
  postgres_db:
    image: postgres:17.3-alpine3.21
    container_name: postgres_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - homie_net
    env_file:
      - config/dev/postgres.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7-alpine
    container_name: homie_redis
    volumes:
      - redis_data:/data
    networks:
      - homie_net
    ports:
      - "6379:6379"
    env_file:
      - config/dev/redis.env
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  homie_api:
    container_name: homie_api
    build:
      context: .
      dockerfile: ./dockerfiles/api.dockerfile
    env_file:
      - config/dev/api.env
    networks:
      - homie_net
    ports:
      - "8080:8080"
    depends_on:
      postgres_db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:8080/ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  tg_bot:
    container_name: tg_bot
    build:
      context: .
      dockerfile: ./dockerfiles/bot.dockerfile
    env_file:
      - config/dev/bot.env
    networks:
      - homie_net
    depends_on:
      homie_api:
        condition: service_healthy
      redis:
        condition: service_healthy

networks:
  homie_net:
    driver: bridge

volumes:
  db_data:
  redis_data: